/*
  # Yönetim Modülü Tabloları
  
  1. Yeni Tablolar:
     - cities (İller)
     - titles (Unvanlar)
     - teams (Ekipler)
  
  2. Güncellemeler (profiles tablosu):
     - city_id (cities tablosuna FK)
     - title_id (titles tablosuna FK)
     - team_id (teams tablosuna FK)
     - expo_push_token (Bildirimler için)
     - phone (Telefon numarası)
     - is_admin (Yönetici kontrolü için)
*/

-- İller tablosu
CREATE TABLE IF NOT EXISTS cities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Örnek İl Verileri
INSERT INTO cities (name) VALUES 
('İstanbul'), ('Ankara'), ('İzmir'), ('Bursa'), ('Antalya'), ('Adana'), ('Gaziantep');

-- Unvanlar tablosu
CREATE TABLE IF NOT EXISTS titles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Örnek Unvan Verileri
INSERT INTO titles (name) VALUES 
('Saha Operasyon Uzmanı'), ('Satış Temsilcisi'), ('Teknik Destek Uzmanı'), ('Bölge Müdürü'), ('Takım Lideri');

-- Ekipler tablosu
CREATE TABLE IF NOT EXISTS teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  leader_id uuid REFERENCES auth.users(id), -- Ekip lideri (Profile id ile aynı)
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Profiles tablosuna yeni alanların eklenmesi
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS city_id bigint REFERENCES cities(id),
ADD COLUMN IF NOT EXISTS title_id bigint REFERENCES titles(id),
ADD COLUMN IF NOT EXISTS team_id bigint REFERENCES teams(id),
ADD COLUMN IF NOT EXISTS expo_push_token text,
ADD COLUMN IF NOT EXISTS phone text,
ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;

-- Herhangi bir RLS (Row Level Security) politikası İSTENMEDİĞİ için eklemiyoruz.
-- Ancak tabloların erişilebilir olması için public yetkisi veriyoruz (Supabase default ayarına göre değişebilir ama garanti olsun).

GRANT ALL ON TABLE cities TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE titles TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE teams TO postgres, anon, authenticated, service_role;
GRANT ALL ON TABLE profiles TO postgres, anon, authenticated, service_role;

-- Sequence izinleri (ID artışı hatası almamak için)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;